# Generated by Django 4.1.3 on 2022-12-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controversial_foods', '0002_alter_appuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
